# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest' 

variables:
  imageName: 'pipelines-javascript-docker'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub'
    command: 'login'
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: app/Dockerfile
- task: Docker@2
  inputs:
    containerRegistry: 'aquareg'
    command: 'login'
- script: 
    docker images
  displayName: 'List Docker Images'
- task: aquasecScanner@4
  inputs:
    image: 'pipelines-javascript-docker:$(Build.BuildId)'
    scanType: 'local'
    containerRuntime: 'docker'
    register: false
    hideBase: false
    showNegligible: false
    windowsScannerVersion: '6.5.0'
    scanner: 'registry.aquasec.com/scanner:2022.4.373'
    runOptions: '-e AQUA-TOKEN= c37eeff4ef6c94ba039a0fbd00a0054011a1db86 -e SCALOCK_LOG_LEVEL=DEBUG'
    connection: 'aqua'